"""Generate thesis_32.docx/pdf from thesis_31 with one methodology figure.

This is a documentation-only generator. It does not run PPO, WP5, WP6, detector
robustness, ablations, or any performance experiment. It inserts an
illustrative synthetic-environment figure generated by
scripts/figures/gen_synthetic_environment_figure.py.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from copy import deepcopy
from pathlib import Path

from docx import Document
from docx.table import _Row
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "manuscript" / "thesis_31.docx"
DST = ROOT / "manuscript" / "thesis_32.docx"
PDF = ROOT / "manuscript" / "thesis_32.pdf"
FIGURE = ROOT / "results" / "plots" / "thesis_32" / "fig_synthetic_environment.png"

INSERT_HEADING = "2.3.1 Illustrative Synthetic Environment Path"
INSERT_TEXT = (
    "This subsection visualizes one deterministic synthetic path generated under the canonical HFMM environment "
    "configuration. The figure is included to make the simulated market environment transparent: the mid-price evolves "
    "under a regime-switching arithmetic Brownian-motion process, the realized-volatility signal is computed from rolling "
    "mid-price changes, and the latent Markov regime switches between low, medium, and high volatility states. The dashed "
    "vertical line marks the chronological 70/30 train-test split used in the out-of-sample protocol. The figure is "
    "illustrative of the methodology only and is not a new performance result."
)
CAPTION = (
    "Figure 2.1. Illustrative synthetic HFMM environment path. The upper panel shows the generated mid-price path. "
    "The middle panel compares the rolling realized-volatility signal observed by the policy with the true "
    "regime-dependent volatility level. The lower panel shows the latent Markov volatility-regime sequence. The dashed "
    "vertical line marks the chronological 70/30 train-test split used for out-of-sample evaluation. This figure is "
    "generated by scripts/figures/gen_synthetic_environment_figure.py and is a methodology illustration, not a regenerated "
    "performance artifact."
)


def replace_text_in_paragraph(paragraph, old: str, new: str) -> None:
    full_text = "".join(run.text for run in paragraph.runs)
    if old not in full_text:
        return
    replaced = full_text.replace(old, new)
    if paragraph.runs:
        paragraph.runs[0].text = replaced
        for run in paragraph.runs[1:]:
            run.text = ""
    else:
        paragraph.add_run(replaced)


def replace_visible_version_refs(doc: Document) -> None:
    replacements = [
        (
            "The thesis_31 adaptation reuses frozen results. It does not rerun PPO, WP5, WP6, figure scripts, "
            "or protected CSV generation. Protected evidence hashes are documented in `EVIDENCE_MANIFEST.md` and "
            "repeated in the reproducibility checklist.",
            "The thesis_32 adaptation reuses frozen performance results. It does not rerun PPO training, WP5/WP6 "
            "experiments, detector robustness, ablations, protected CSV generation, or frozen performance-figure "
            "generation. The only newly generated visual is the methodology-only synthetic-environment illustration "
            "produced by `scripts/figures/gen_synthetic_environment_figure.py`.",
        ),
        (
            "No PPO/WP5/WP6 reruns or figure regeneration during template adaptation.",
            "No PPO/WP5/WP6 reruns and no frozen evidence-figure regeneration; only the methodology-only "
            "synthetic-environment illustration was generated.",
        ),
        ("manuscript/thesis_30.pdf / .docx", "manuscript/thesis_31.pdf / .docx"),
        ("thesis_31", "thesis_32"),
    ]
    all_paragraphs = list(doc.paragraphs)
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                all_paragraphs.extend(cell.paragraphs)
    for section in doc.sections:
        all_paragraphs.extend(section.header.paragraphs)
        all_paragraphs.extend(section.footer.paragraphs)

    for paragraph in all_paragraphs:
        for old, new in replacements:
            replace_text_in_paragraph(paragraph, old, new)


def set_row_text(row, label: str, value: str) -> None:
    row.cells[0].text = label
    row.cells[1].text = value


def update_front_page_references(doc: Document) -> None:
    front_table = doc.tables[0]
    frozen_idx = None
    for idx, row in enumerate(front_table.rows):
        if row.cells[0].text.strip() == "Frozen baseline":
            frozen_idx = idx
            break
    if frozen_idx is None:
        raise RuntimeError("Could not find Frozen baseline row in front-page table")

    new_tr = deepcopy(front_table.rows[frozen_idx]._tr)
    front_table.rows[frozen_idx]._tr.addprevious(new_tr)
    current_row = _Row(new_tr, front_table)
    set_row_text(current_row, "Current draft", "manuscript/thesis_32.pdf / .docx")

    rows = front_table.rows
    set_row_text(rows[frozen_idx + 1], "Previous source draft", "manuscript/thesis_31.pdf / .docx")
    set_row_text(rows[frozen_idx + 2], "Frozen baseline", "manuscript/thesis_29.pdf, tag thesis-v29-frozen")
    set_row_text(rows[frozen_idx + 3], "Decision log", "manuscript/decisions_log_13.pdf")


def find_paragraph(doc: Document, exact_text: str):
    for paragraph in doc.paragraphs:
        if paragraph.text.strip() == exact_text:
            return paragraph
    raise RuntimeError(f"Could not find insertion anchor: {exact_text}")


def insert_paragraph_before(doc: Document, ref_para, text: str = "", style: str | None = None):
    paragraph = doc.add_paragraph(text, style=style)
    ref_para._p.addprevious(paragraph._p)
    return paragraph


def insert_picture_before(doc: Document, ref_para, image_path: Path, width_inches: float):
    paragraph = doc.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph.paragraph_format.keep_with_next = True
    paragraph.paragraph_format.keep_together = True
    paragraph.add_run().add_picture(str(image_path), width=Inches(width_inches))
    ref_para._p.addprevious(paragraph._p)
    return paragraph


def insert_methodology_figure(doc: Document) -> None:
    if not FIGURE.exists():
        raise FileNotFoundError(f"Missing methodology figure: {FIGURE}")

    ref = find_paragraph(doc, "2.4 Limit-Order Fill Model")

    caption = insert_paragraph_before(doc, ref, CAPTION, style="Caption")
    caption.alignment = WD_ALIGN_PARAGRAPH.CENTER
    caption.paragraph_format.keep_together = True

    picture = insert_picture_before(doc, caption, FIGURE, width_inches=6.15)
    body = insert_paragraph_before(doc, picture, INSERT_TEXT)
    body.paragraph_format.keep_with_next = True

    heading = insert_paragraph_before(doc, body, INSERT_HEADING, style="Heading 3")
    heading.paragraph_format.keep_with_next = True


def export_pdf_with_word() -> None:
    tmp_pdf = PDF.with_name(PDF.stem + "_export_tmp.pdf")
    if tmp_pdf.exists():
        tmp_pdf.unlink()
    ps = (
        "$ErrorActionPreference = 'Stop'; "
        f"$tmp = '{str(tmp_pdf)}'; "
        "if (Test-Path -LiteralPath $tmp) { Remove-Item -LiteralPath $tmp -Force }; "
        "$word = New-Object -ComObject Word.Application; "
        "$word.Visible = $false; "
        "try { "
        f"$doc = $word.Documents.Open('{str(DST)}', $false, $true); "
        "$doc.ExportAsFixedFormat($tmp, 17); "
        "$doc.Close($false); "
        "} finally { $word.Quit() }; "
        f"Move-Item -LiteralPath $tmp -Destination '{str(PDF)}' -Force"
    )
    subprocess.run(
        ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps],
        cwd=str(ROOT),
        check=True,
        capture_output=True,
        text=True,
    )


def export_pdf_with_libreoffice() -> None:
    soffice = shutil.which("soffice")
    if not soffice:
        raise RuntimeError("LibreOffice soffice not found on PATH")
    subprocess.run(
        [
            soffice,
            "--headless",
            "--convert-to",
            "pdf",
            "--outdir",
            str(PDF.parent),
            str(DST),
        ],
        cwd=str(ROOT),
        check=True,
        capture_output=True,
        text=True,
    )


def export_pdf() -> bool:
    try:
        export_pdf_with_libreoffice()
        return True
    except Exception as lo_err:
        print(f"LibreOffice PDF export unavailable or failed: {lo_err}")

    if sys.platform.startswith("win"):
        try:
            export_pdf_with_word()
            return True
        except Exception as word_err:
            print(f"Microsoft Word PDF export failed: {word_err}")
    return False


def main() -> int:
    if not SRC.exists():
        raise FileNotFoundError(SRC)
    if not FIGURE.exists():
        raise FileNotFoundError(
            f"{FIGURE} does not exist. Run scripts/figures/gen_synthetic_environment_figure.py first."
        )

    shutil.copy2(SRC, DST)
    doc = Document(DST)
    replace_visible_version_refs(doc)
    update_front_page_references(doc)
    insert_methodology_figure(doc)
    doc.save(DST)
    print(f"Wrote {DST.relative_to(ROOT)}")

    if export_pdf():
        print(f"Wrote {PDF.relative_to(ROOT)}")
    else:
        print(f"PDF export failed; DOCX remains available at {DST.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
