"""Generate thesis_33.docx/pdf from thesis_32 with academic-polish edits.

This is a documentation-only generator. It does not run PPO, WP5, WP6, detector
robustness, ablations, misspecification, or protected evidence pipelines. It
keeps the frozen performance evidence unchanged and adds only reader-facing
academic polish plus a methodology-only pipeline illustration generated by
scripts/figures/gen_pipeline_architecture_figure.py.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "manuscript" / "thesis_32.docx"
DST = ROOT / "manuscript" / "thesis_33.docx"
PDF = ROOT / "manuscript" / "thesis_33.pdf"
PIPELINE_FIGURE = ROOT / "results" / "plots" / "thesis_33" / "fig_pipeline_architecture.png"

PIPELINE_HEADING = "4.6 Methodology Pipeline Illustration"
PIPELINE_TEXT = (
    "Figure 4.1 summarizes the evidence pipeline at a methodological level. A synthetic path generates the latent "
    "volatility regime and mid-price sequence; rolling realized volatility and detector labels form the observed "
    "signals; the Gymnasium environment converts these signals, inventory, time, quotes, and fills into sequential "
    "observations and rewards; PPO variants and analytical baselines are then evaluated on held-out out-of-sample "
    "metrics. The figure is included only to clarify the workflow and is not a regenerated performance artifact."
)
PIPELINE_CAPTION = (
    "Figure 4.1. Methodology-only HFMM evaluation pipeline. Synthetic market paths produce sigma_hat and regime_hat "
    "signals, which feed the Gymnasium environment, PPO variants, baselines, and out-of-sample metrics. Generated by "
    "scripts/figures/gen_pipeline_architecture_figure.py; this illustration is not performance evidence."
)


LIT_REVIEW_PARAS = [
    (
        "The literature relevant to this thesis falls into four connected strands: classical inventory-aware market "
        "making, reinforcement-learning market making, volatility regimes and non-stationarity, and statistical "
        "interpretation of small or practically negligible differences. The purpose of the review is not to claim a "
        "new analytical quoting rule or a new reinforcement-learning algorithm. It is to locate a narrower "
        "information-design question inside an established market-making literature."
    ),
    (
        "Classical market-making models provide the inventory-risk and quote-placement foundation. A market maker "
        "earns spread income by posting bid and ask quotes, but stochastic execution creates inventory exposure whose "
        "value changes with the mid-price. Avellaneda and Stoikov (2008) formalize this tradeoff through a "
        "reservation price and spread term that depend on inventory, risk aversion, volatility, remaining horizon, "
        "and order-arrival intensity. Gueant, Lehalle and Fernandez-Tapia (2013) extend this inventory-control view "
        "and provide tractable approximations for optimal quotes under inventory constraints."
    ),
    (
        "This analytical literature motivates the thesis design in two direct ways: it explains why inventory, "
        "volatility, quote distance, and fill intensity are central state variables, and it supplies the "
        "Avellaneda-Stoikov baseline used as a non-learning comparator. Related preprints by Fodra and Labadie "
        "(2012, 2013) are useful additional context for inventory-constrained and state-dependent market-making "
        "models, but they are treated cautiously as preprints. The thesis does not attempt to derive a new "
        "closed-form quoting rule; it uses the analytical tradition to frame the simulation and benchmark design."
    ),
    (
        "A second strand replaces closed-form rules with learned policies. Spooner et al. (2018) demonstrate that "
        "reinforcement learning can learn market-making behavior in a simulated limit-order-book setting and show "
        "why reward design and inventory control matter. Spooner and Savani (2020) extend the discussion toward "
        "robustness under adversarially varied market conditions. These studies support the use of simulator-based "
        "evaluation for learned quoting policies, while also showing that market-making performance can be sensitive "
        "to the assumptions used to generate training and evaluation episodes."
    ),
    (
        "Deep reinforcement-learning studies with market signals are closest to the present information-design "
        "question. Gasperov and Kostanjcar (2021) study market making with signals through deep reinforcement "
        "learning; Gasperov et al. (2021) review reinforcement-learning approaches to optimal market making; and "
        "Gasperov and Kostanjcar (2022) train agents in a richer Hawkes-process limit-order-book simulator. This "
        "literature motivates learned quoting, state representation, reward shaping, robustness checks, and "
        "simulator-based evidence. The present thesis is narrower: PPO is used as a controlled testbed for whether "
        "one additional volatility-regime channel has incremental value, not as a claim of algorithmic optimality."
    ),
    (
        "Volatility regimes and non-stationarity are economically meaningful. A high-volatility state can increase "
        "inventory risk, change fill-risk tradeoffs, and make a quote width that was appropriate in a calm period "
        "too aggressive in a turbulent period. The thesis therefore models a latent three-state Markov volatility "
        "process and a causal rolling realized-volatility detector. This design should not be read as a claim that "
        "volatility regimes are irrelevant. The tested question is more specific: whether categorical regime labels "
        "add incremental value once the policy already observes a continuous realized-volatility estimate."
    ),
    (
        "The key state-representation issue is redundancy. The continuous signal sigma_hat gives the PPO policy a "
        "graded estimate of recent realized volatility. A low/medium/high label derived from related volatility "
        "information may help if it summarizes latent structure that sigma_hat does not expose, but it may add little "
        "if the continuous signal already contains the useful variation for quote placement. This gives the exact "
        "gap addressed by the thesis: When a PPO market-making policy already observes a continuous "
        "realized-volatility estimate, does adding an explicit categorical volatility-regime label improve "
        "out-of-sample performance in a controlled synthetic HFMM environment?"
    ),
    (
        "Finally, the empirical interpretation requires care because the thesis evaluates an incremental signal, not "
        "the existence of volatility effects in general. Lakens (2017) and Lakens, Scheel and Isager (2018) motivate "
        "equivalence testing as a way to distinguish a merely non-significant difference from evidence that a "
        "difference is small relative to a pre-specified practical bound. The TOST framing is therefore used as "
        "background for the later statistics section; it does not by itself prove that labels contain no information."
    ),
]


SYNTHETIC_BOUNDARY_PARAS = [
    (
        "The result is bounded to the tested synthetic HFMM simulator. The simulator deliberately isolates quote "
        "distance, Poisson-arrival fills, fees, latency, inventory, and volatility regimes so that the incremental "
        "information value of the regime channel can be tested cleanly."
    ),
    (
        "Real limit-order books include additional mechanisms that are outside the main simulator: queue position, "
        "execution priority, adverse selection, order-book imbalance, richer latency effects, clustered or "
        "self-exciting order arrivals, non-stationary liquidity, and exchange-specific transaction-cost and "
        "microstructure rules. These mechanisms can change both the value of volatility information and the way a "
        "categorical regime label interacts with execution risk."
    ),
    (
        "For that reason, the thesis should be read as controlled synthetic evidence, not as a real-market external "
        "validity claim. Richer LOB simulators, Hawkes-process LOB models, queue-reactive execution, and real-data "
        "evaluation are natural future work and could change the incremental value of regime labels."
    ),
]


def iter_all_paragraphs(doc: Document):
    paragraphs = list(doc.paragraphs)
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                paragraphs.extend(cell.paragraphs)
    for section in doc.sections:
        paragraphs.extend(section.header.paragraphs)
        paragraphs.extend(section.footer.paragraphs)
    return paragraphs


def replace_text_in_paragraph(paragraph, old: str, new: str) -> None:
    full_text = "".join(run.text for run in paragraph.runs)
    if old not in full_text:
        return
    replaced = full_text.replace(old, new)
    if paragraph.runs:
        paragraph.runs[0].text = replaced
        for run in paragraph.runs[1:]:
            run.text = ""
    else:
        paragraph.add_run(replaced)


def clean_encoding_artifacts(doc: Document) -> None:
    replacements = {
        "\ufffe": "-",
        "\u00ad": "-",
        "\ufffd": "",
        "limit\ufffeorder": "limit-order",
        "out-of\ufffesample": "out-of-sample",
        "Sharpe\ufffelike": "Sharpe-like",
        "one\ufffehot": "one-hot",
        "limit\u00adorder": "limit-order",
        "out-of\u00adsample": "out-of-sample",
        "Sharpe\u00adlike": "Sharpe-like",
        "one\u00adhot": "one-hot",
        "limitï¿¾order": "limit-order",
        "out-ofï¿¾sample": "out-of-sample",
        "Sharpeï¿¾like": "Sharpe-like",
        "oneï¿¾hot": "one-hot",
    }
    for paragraph in iter_all_paragraphs(doc):
        for run in paragraph.runs:
            if run._r.xpath(".//w:drawing"):
                continue
            text = run.text
            for old, new in replacements.items():
                text = text.replace(old, new)
            if text != run.text:
                run.text = text


def disable_auto_hyphenation(doc: Document) -> None:
    settings = doc.settings.element
    for element in settings.findall(qn("w:autoHyphenation")):
        settings.remove(element)
    auto_hyphenation = OxmlElement("w:autoHyphenation")
    auto_hyphenation.set(qn("w:val"), "false")
    settings.append(auto_hyphenation)

    for paragraph in iter_all_paragraphs(doc):
        p_pr = paragraph._p.get_or_add_pPr()
        if p_pr.find(qn("w:suppressAutoHyphens")) is None:
            suppress = OxmlElement("w:suppressAutoHyphens")
            suppress.set(qn("w:val"), "true")
            p_pr.append(suppress)


def simplify_dense_table_labels(doc: Document) -> None:
    replacements = {
        "Observation meaning": "Signals",
        "Mean Sharpe-like": "Sharpe-like",
        "Mean final equity": "Final equity",
        "Mean inv_p99": "inv_p99",
        "Mean fill rate": "Fill rate",
        "continuous sigma_hat only": "sigma_hat only",
        "sigma_hat + true regime one-hot": "sigma_hat + regime_true",
        "estimated regime one-hot only": "regime_hat only",
        "sigma_hat + estimated regime one-hot": "sigma_hat + regime_hat",
        "true regime one-hot only": "regime_true only",
    }
    for paragraph in iter_all_paragraphs(doc):
        for old, new in replacements.items():
            replace_text_in_paragraph(paragraph, old, new)


def replace_visible_version_refs(doc: Document) -> None:
    replacements = [
        (
            "This report studies whether explicit volatility-regime information improves a PPO-based high-frequency "
            "market-making agent in a controlled synthetic limit-order-book environment.",
            "This report studies whether explicit volatility-regime information improves a Proximal Policy Optimization "
            "(PPO)-based high-frequency market-making (HFMM) agent in a controlled synthetic limit-order-book (LOB) "
            "environment.",
        ),
        (
            "The evidence comes from the canonical WP5/WP6 experiments:",
            "The evidence comes from the canonical frozen experiments:",
        ),
        (
            "The report makes no live-trading deployment claim and does not claim to prove the internal PPO mechanism.",
            "The report makes no production-deployment claim and does not claim to prove the internal PPO mechanism.",
        ),
        (
            "The thesis is a controlled synthetic-market study. It does not claim live trading viability, real-order-book external validity, or a proven PPO representation mechanism. The result is conditional on the simulator, signal design, PPO hyperparameters, and degradation calibration tested here.",
            "The thesis is a controlled synthetic-market study. It does not claim production deployment viability, real-order-book external validity, or a proven PPO representation mechanism. The result is conditional on the simulator, signal design, PPO hyperparameters, and degradation calibration tested here.",
        ),
        (
            "The thesis_32 adaptation reuses frozen performance results. It does not rerun PPO training, WP5/WP6 "
            "experiments, detector robustness, ablations, protected CSV generation, or frozen performance-figure "
            "generation. The only newly generated visual is the methodology-only synthetic-environment illustration "
            "produced by `scripts/figures/gen_synthetic_environment_figure.py`.",
            "The thesis_33 adaptation reuses frozen performance results. It does not rerun PPO training, WP5/WP6 "
            "experiments, detector robustness, ablations, misspecification checks, protected CSV generation, or frozen "
            "performance-figure generation. The only newly generated visuals are methodology-only illustrations "
            "produced by `scripts/figures/gen_synthetic_environment_figure.py` and "
            "`scripts/figures/gen_pipeline_architecture_figure.py`.",
        ),
        (
            "Evaluation writes CSV metrics, figures, and summaries. The thesis_32 adaptation embeds existing figures "
            "and quotes frozen numerical evidence; it does not regenerate evidence artifacts.",
            "Evaluation writes CSV metrics, figures, and summaries. The thesis_33 adaptation embeds existing figures "
            "and quotes frozen numerical evidence; it does not regenerate protected evidence artifacts.",
        ),
        (
            "These commands document reproducibility paths only; thesis_32 adaptation did not rerun experiments.",
            "These commands document reproducibility paths only; thesis_33 adaptation did not rerun experiments.",
        ),
        ("Template-adapted draft; frozen evidence is not regenerated.", "Academic-polish draft; frozen evidence is not regenerated."),
        ("thesis_32", "thesis_33"),
    ]
    for paragraph in iter_all_paragraphs(doc):
        for old, new in replacements:
            replace_text_in_paragraph(paragraph, old, new)


def set_row_text(row, label: str, value: str) -> None:
    row.cells[0].text = label
    row.cells[1].text = value


def update_front_page_references(doc: Document) -> None:
    front_table = doc.tables[0]
    updates = {
        "Current draft": "manuscript/thesis_33.pdf / .docx",
        "Previous source draft": "manuscript/thesis_32.pdf / .docx",
        "Frozen baseline": "manuscript/thesis_29.pdf, tag thesis-v29-frozen",
        "Decision log": "manuscript/decisions_log_13.pdf",
    }
    found = set()
    for row in front_table.rows:
        label = row.cells[0].text.strip()
        if label in updates:
            set_row_text(row, label, updates[label])
            found.add(label)
    missing = sorted(set(updates) - found)
    if missing:
        raise RuntimeError(f"Missing front-page metadata rows: {missing}")


def find_paragraph(doc: Document, exact_text: str):
    for paragraph in doc.paragraphs:
        if paragraph.text.strip() == exact_text:
            return paragraph
    raise RuntimeError(f"Could not find paragraph: {exact_text}")


def insert_paragraph_before(doc: Document, ref_para, text: str = "", style: str | None = None):
    paragraph = doc.add_paragraph(text, style=style)
    ref_para._p.addprevious(paragraph._p)
    return paragraph


def delete_paragraph(paragraph) -> None:
    element = paragraph._element
    element.getparent().remove(element)
    paragraph._p = paragraph._element = None


def replace_section_body(doc: Document, heading_text: str, next_heading_text: str, paragraphs: list[str]) -> None:
    heading = find_paragraph(doc, heading_text)
    next_heading = find_paragraph(doc, next_heading_text)
    in_range = False
    to_delete = []
    for paragraph in doc.paragraphs:
        if paragraph._p is heading._p:
            in_range = True
            continue
        if paragraph._p is next_heading._p:
            break
        if in_range:
            to_delete.append(paragraph)
    for paragraph in to_delete:
        delete_paragraph(paragraph)
    for text in paragraphs:
        insert_paragraph_before(doc, next_heading, text)


def insert_paragraphs_after(doc: Document, anchor_text: str, paragraphs: list[str]) -> None:
    anchor = find_paragraph(doc, anchor_text)
    for text in reversed(paragraphs):
        paragraph = doc.add_paragraph(text)
        anchor._p.addnext(paragraph._p)


def insert_picture_before(doc: Document, ref_para, image_path: Path, width_inches: float):
    paragraph = doc.add_paragraph()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph.paragraph_format.keep_with_next = True
    paragraph.paragraph_format.keep_together = True
    paragraph.add_run().add_picture(str(image_path), width=Inches(width_inches))
    ref_para._p.addprevious(paragraph._p)
    return paragraph


def replace_exact_paragraph(doc: Document, old: str, new: str) -> None:
    paragraph = find_paragraph(doc, old)
    paragraph.text = new


def rename_heading(doc: Document, old: str, new: str) -> None:
    find_paragraph(doc, old).text = new


def apply_reader_facing_replacements(doc: Document) -> None:
    replacements = {
        "Estimated regime labels are assigned by thresholding sigma_hat after a warmup period. The main WP4/WP5/WP6 pipelines use the causal rv_baseline detector. The rv_dwell detector is retained only as an auxiliary/offline robustness comparison, while the HMM detector is an additional robustness variant.": (
            "Estimated regime labels are assigned by thresholding sigma_hat after a warmup period. The main reported "
            "training and evaluation pipelines use the causal rv_baseline detector. The rv_dwell detector is retained "
            "only as an auxiliary/offline robustness comparison, while the HMM detector is an additional robustness "
            "variant."
        ),
        "WP4 trains PPO policies; WP5 evaluates strategies and ablations; WP6 runs the signal-informativeness sweep. The fixed-spread and AS baselines provide non-learning comparators.": (
            "The training layer fits PPO policies, the main evaluation layer compares strategies and ablations, and "
            "the signal-informativeness layer tests whether regime labels gain value as sigma_hat is degraded. The "
            "fixed-spread and AS baselines provide non-learning comparators."
        ),
        "WP5 and WP6 use a chronological 70/30 split on the exogenous series. PPO trains on the first segment and is evaluated deterministically on the held-out OOS segment.": (
            "The main out-of-sample evaluation and signal-informativeness sweep use a chronological 70/30 split on "
            "the exogenous series. PPO trains on the first segment and is evaluated deterministically on the held-out "
            "OOS segment."
        ),
        "The main WP5 comparison evaluates naive, AS, ppo_aware, and ppo_blind. The ablation and WP6 designs use sigma_only, regime_only, combined, oracle_pure, and oracle_full.": (
            "Experiment 1, the Main Out-of-Sample Evaluation, evaluates naive, AS, ppo_aware, and ppo_blind. "
            "Experiment 2, the Five-Variant Signal Ablation, and Experiment 5, the Signal-Informativeness Sweep, use "
            "sigma_only, regime_only, combined, oracle_pure, and oracle_full."
        ),
        "The main 20-seed OOS evaluation shows that PPO variants produce much higher risk-adjusted performance than the fixed-spread and AS baselines. AS can produce higher raw equity, but with substantially larger inventory exposure.": (
            "Experiment 1, the 20-seed Main Out-of-Sample Evaluation, shows that PPO variants produce much higher "
            "risk-adjusted performance than the fixed-spread and AS baselines. AS can produce higher raw equity, but "
            "with substantially larger inventory exposure."
        ),
        "The detector robustness table comes from the w5_detector_full robustness experiment, while the main WP5 OOS table in Section 8.1 comes from the w5_main experiment. Small differences in PPO-aware/blind means therefore reflect distinct frozen experiment batches, not an inconsistency.": (
            "The detector robustness table comes from Experiment 3, the Detector Robustness experiment "
            "(w5_detector_full), while the main OOS table in Section 8.1 comes from Experiment 1 (w5_main). Small "
            "differences in PPO-aware/blind means therefore reflect distinct frozen experiment batches, not an "
            "inconsistency."
        ),
        "WP6 did not support the original informativeness-threshold hypothesis within the tested calibration band. sigma_only remained high under informative conditions, while combined was directionally below sigma_only.": (
            "Experiment 5, the Signal-Informativeness Sweep, did not support the original informativeness-threshold "
            "hypothesis within the tested calibration band. sigma_only remained high under informative conditions, "
            "while combined was directionally below sigma_only."
        ),
        "The WP6 figures should be read as a refinement of the main finding rather than a new mechanism proof: they show that the tested sigma_hat degradation path did not reveal a regime-label advantage.": (
            "The Signal-Informativeness Sweep figures should be read as a refinement of the main finding rather than "
            "a new mechanism proof: they show that the tested sigma_hat degradation path did not reveal a "
            "regime-label advantage."
        ),
        "TOST evaluates whether the plausible range of a paired difference lies inside a pre-specified practical-equivalence band. At alpha = 0.05, the corresponding equivalence reading uses the 90% confidence interval. WP5 uses TOST to support practical equivalence for sigma_only versus oracle_full; WP6 also uses related paired tests to examine non-equivalence and mean indistinguishability patterns.": (
            "TOST evaluates whether the plausible range of a paired difference lies inside a pre-specified "
            "practical-equivalence band. At alpha = 0.05, the corresponding equivalence reading uses the 90% "
            "confidence interval. The Five-Variant Signal Ablation uses TOST to support practical equivalence for "
            "sigma_only versus oracle_full; the Signal-Informativeness Sweep also uses related paired tests to "
            "examine non-equivalence and mean indistinguishability patterns."
        ),
        "The conclusion does not rest only on p > 0.05. It is supported by detector robustness, oracle labels, TOST equivalence, reward-channel checks, mild misspecification, and WP6 degradation tests.": (
            "The conclusion does not rest only on p > 0.05. It is supported by detector robustness, oracle labels, "
            "TOST equivalence, reward-channel checks, mild misspecification, and signal-degradation tests."
        ),
        "The table below summarizes supporting diagnostics. These items support interpretation and provenance; they do not replace the canonical WP5/WP6 evidence chain used for the main claims.": (
            "The table below summarizes supporting diagnostics. These items support interpretation and provenance; "
            "they do not replace the canonical frozen evidence chain used for the main claims."
        ),
    }
    for old, new in replacements.items():
        replace_exact_paragraph(doc, old, new)

    rename_heading(doc, "6.5 WP6 Signal-Informativeness Sweep", "6.5 Experiment 5: Signal-Informativeness Sweep")
    rename_heading(doc, "8.1 Main WP5 OOS Results", "8.1 Experiment 1: Main Out-of-Sample Evaluation")
    rename_heading(doc, "8.5 WP6 Signal-Informativeness Sweep", "8.5 Experiment 5: Signal-Informativeness Sweep")

    caption_replacements = {
        "Figure 1. Main WP5 OOS results: PPO variants dominate naive and AS on risk-adjusted performance, while AS carries much larger inventory tail risk.": (
            "Figure 8.1. Experiment 1 main OOS results: PPO variants dominate naive and AS on risk-adjusted performance, "
            "while AS carries much larger inventory tail risk."
        ),
        "Figure 2. Seed-paired PPO-aware versus PPO-blind comparison: the estimated regime channel does not create a robust Sharpe-like advantage.": (
            "Figure 8.2. Seed-paired PPO-aware versus PPO-blind comparison: the estimated regime channel does not "
            "create a robust Sharpe-like advantage."
        ),
        "Figure 3. Five-variant ablation summary: sigma_only is the strongest mean Sharpe-like variant, and adding categorical labels does not improve it.": (
            "Figure 8.3. Five-variant ablation summary: sigma_only is the strongest mean Sharpe-like variant, and "
            "adding categorical labels does not improve it."
        ),
        "Figure 4. Oracle-label paired-seed comparison: even true regime labels do not reliably improve on sigma_hat alone.": (
            "Figure 8.4. Oracle-label paired-seed comparison: even true regime labels do not reliably improve on "
            "sigma_hat alone."
        ),
        "Figure 5. Detector robustness: rv_baseline, rv_dwell, and HMM all fail to create a reliable regime-aware PPO advantage.": (
            "Figure 8.5. Detector robustness: rv_baseline, rv_dwell, and HMM all fail to create a reliable "
            "regime-aware PPO advantage."
        ),
        "Figure 6. Regime-conditional eta summary: changing the reward channel by regime still favors sigma_only over combined.": (
            "Figure 8.6. Regime-conditional eta summary: changing the reward channel by regime still favors "
            "sigma_only over combined."
        ),
        "Figure 7. Mild model-misspecification summary: sigma_only and oracle_full remain close under regime-dependent execution parameters.": (
            "Figure 8.7. Mild model-misspecification summary: sigma_only and oracle_full remain close under "
            "regime-dependent execution parameters."
        ),
        "Figure 8. WP6 monotonic-gap plot: the expected narrowing of the sigma_only versus combined gap does not appear in the tested calibration band.": (
            "Figure 8.8. Experiment 5 monotonic-gap plot: the expected narrowing of the sigma_only versus combined gap "
            "does not appear in the tested calibration band."
        ),
        "Figure 9. WP6 paired-seed combined versus sigma_only: combined is directionally below sigma_only in informative conditions.": (
            "Figure 8.9. Experiment 5 paired-seed combined versus sigma_only: combined is directionally below sigma_only "
            "in informative conditions."
        ),
        "Figure 10. WP6 paired-seed combined versus regime_only: this diagnostic bounds how much sigma_hat is used inside the combined variant.": (
            "Figure 8.10. Experiment 5 paired-seed combined versus regime_only: this diagnostic bounds how much "
            "sigma_hat is used inside the combined variant."
        ),
    }
    for paragraph in iter_all_paragraphs(doc):
        for old, new in caption_replacements.items():
            replace_text_in_paragraph(paragraph, old, new)


def apply_formula_explanations(doc: Document) -> None:
    insert_paragraphs_after(
        doc,
        "Here lambda(delta) is the fill intensity at quote distance delta, A is the baseline arrival scale, and k controls the exponential decay as quotes move farther from the mid-price.",
        [
            (
                "Intuitively, quotes closer to the mid-price fill more often because they are more attractive to "
                "incoming market orders. Quotes farther away earn more spread if they fill, but the exponential "
                "intensity makes those fills less likely."
            )
        ],
    )
    insert_paragraphs_after(
        doc,
        "Here h_idx and m_idx are the two discrete PPO action components, h is the half-spread in ticks, and m is the quote skew in ticks.",
        [
            (
                "The half-spread h controls quote width and aggressiveness: small h is more aggressive and large h is "
                "more passive. The skew m shifts the bid and ask distances asymmetrically, allowing the policy to lean "
                "against inventory or other state pressure while still quoting both sides."
            )
        ],
    )
    insert_paragraphs_after(
        doc,
        "Here R_t is the reward and eta is the inventory-penalty coefficient. Fees are included in the cash update and are not counted a second time in the reward.",
        [
            (
                "The eta q^2 term discourages the agent from earning apparent PnL by accumulating large directional "
                "inventory. It connects the learning objective to market-making risk control rather than pure "
                "speculation on the mid-price path."
            )
        ],
    )


def apply_markov_matrix(doc: Document) -> None:
    insert_paragraphs_after(
        doc,
        "Here z_t is the latent volatility regime at step t, L/M/H denote low, medium, and high volatility, and P_ij is the sticky transition probability from regime i to regime j.",
        [
            "(2a)  P = [[0.9967, 0.0023, 0.0010], [0.0042, 0.9917, 0.0041], [0.0010, 0.0030, 0.9960]]",
            (
                "Rows correspond to the current regime L/M/H, and columns correspond to the next regime L/M/H. The "
                "large diagonal probabilities make the regimes persistent, or sticky, so volatility states tend to "
                "last for many steps rather than switching erratically."
            ),
            (
                "This persistence matters because rolling realized-volatility detection is only meaningful when "
                "regime-dependent volatility differences last long enough to be observed through a finite window."
            ),
        ],
    )


def apply_ppo_rationale(doc: Document) -> None:
    insert_paragraphs_after(
        doc,
        "Here theta denotes policy parameters, rho_t(theta) is the PPO probability ratio, A_hat_t is the advantage estimate, and eps is the clipping parameter. The report uses this only as a concise training-objective reference.",
        [
            (
                "PPO is used because the thesis needs a stable, widely used policy-gradient algorithm for stochastic "
                "sequential control, not because it claims PPO is the best possible market-making RL algorithm. The "
                "action is discrete but two-dimensional MultiDiscrete: the agent chooses half-spread h and skew m, "
                "which together form a 25-action quote grid. DQN would require value-based handling of this grid and "
                "is less natural for the policy-gradient control framing used here; SAC is more naturally aligned "
                "with continuous actions and would expand the scope; and A2C is simpler but often less stable or "
                "sample-efficient than PPO. PPO therefore provides a reliable baseline algorithm for controlled "
                "ablation of the observation channels."
            )
        ],
    )


def apply_scope_and_future_work(doc: Document) -> None:
    replace_section_body(doc, "10.3 Synthetic-Market Boundary", "10.4 Risks to Interpretation", SYNTHETIC_BOUNDARY_PARAS)
    replace_section_body(
        doc,
        "10.5 Future Work",
        "11 Reproducibility Checklist",
        [
            "Evaluate stronger regime-dependent execution misspecification and richer non-stationary liquidity settings.",
            "Test richer limit-order-book simulators with queue position, order-book imbalance, latency priority, adverse selection, and self-exciting order flow.",
            "Use Hawkes-process LOB models and real-data evaluation after thesis scope, not as current claims of this report.",
            "Run representation-level diagnostics only as future mechanism work.",
            "Explore alternative observation encodings and policy architectures.",
        ],
    )


def insert_pipeline_figure(doc: Document) -> None:
    if not PIPELINE_FIGURE.exists():
        raise FileNotFoundError(
            f"{PIPELINE_FIGURE} does not exist. Run scripts/figures/gen_pipeline_architecture_figure.py first."
        )

    ref = find_paragraph(doc, "5 Layered Experimental Model")
    caption = insert_paragraph_before(doc, ref, PIPELINE_CAPTION, style="Caption")
    caption.alignment = WD_ALIGN_PARAGRAPH.CENTER
    caption.paragraph_format.keep_together = True
    picture = insert_picture_before(doc, caption, PIPELINE_FIGURE, width_inches=6.4)
    body = insert_paragraph_before(doc, picture, PIPELINE_TEXT)
    body.paragraph_format.keep_with_next = True
    heading = insert_paragraph_before(doc, body, PIPELINE_HEADING, style="Heading 2")
    heading.paragraph_format.keep_with_next = True


def add_references(doc: Document) -> None:
    ref = find_paragraph(doc, "Spooner, T., Fearnley, J., Savani, R., & Koukorinis, A. (2018). Market Making via Reinforcement Learning. Proceedings of the 17th International Conference on Autonomous Agents and MultiAgent Systems, 434-442.")
    insert_paragraph_before(
        doc,
        ref,
        "Fodra, P., & Labadie, M. (2012). High-frequency market-making with inventory constraints and directional bets. arXiv:1206.4810.",
    )
    insert_paragraph_before(
        doc,
        ref,
        "Fodra, P., & Labadie, M. (2013). High-frequency market-making for multi-dimensional Markov processes. arXiv:1303.7177.",
    )


def export_pdf_with_word() -> None:
    tmp_pdf = PDF.with_name(PDF.stem + "_export_tmp.pdf")
    if tmp_pdf.exists():
        tmp_pdf.unlink()
    ps = (
        "$ErrorActionPreference = 'Stop'; "
        f"$tmp = '{str(tmp_pdf)}'; "
        "if (Test-Path -LiteralPath $tmp) { Remove-Item -LiteralPath $tmp -Force }; "
        "$word = New-Object -ComObject Word.Application; "
        "$word.Visible = $false; "
        "try { "
        f"$doc = $word.Documents.Open('{str(DST)}', $false, $true); "
        "$doc.ExportAsFixedFormat($tmp, 17); "
        "$doc.Close($false); "
        "} finally { $word.Quit() }; "
        f"Move-Item -LiteralPath $tmp -Destination '{str(PDF)}' -Force"
    )
    subprocess.run(
        ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps],
        cwd=str(ROOT),
        check=True,
        capture_output=True,
        text=True,
    )


def export_pdf_with_libreoffice() -> None:
    soffice = shutil.which("soffice")
    if not soffice:
        raise RuntimeError("LibreOffice soffice not found on PATH")
    subprocess.run(
        [
            soffice,
            "--headless",
            "--convert-to",
            "pdf",
            "--outdir",
            str(PDF.parent),
            str(DST),
        ],
        cwd=str(ROOT),
        check=True,
        capture_output=True,
        text=True,
    )


def export_pdf() -> bool:
    try:
        export_pdf_with_libreoffice()
        return True
    except Exception as lo_err:
        print(f"LibreOffice PDF export unavailable or failed: {lo_err}")

    if sys.platform.startswith("win"):
        try:
            export_pdf_with_word()
            return True
        except Exception as word_err:
            print(f"Microsoft Word PDF export failed: {word_err}")
    return False


def main() -> int:
    if not SRC.exists():
        raise FileNotFoundError(SRC)
    if not PIPELINE_FIGURE.exists():
        raise FileNotFoundError(
            f"{PIPELINE_FIGURE} does not exist. Run scripts/figures/gen_pipeline_architecture_figure.py first."
        )

    shutil.copy2(SRC, DST)
    doc = Document(DST)
    replace_visible_version_refs(doc)
    update_front_page_references(doc)
    replace_section_body(doc, "1.3 Background and Related Work", "1.4 Contributions", LIT_REVIEW_PARAS)
    apply_markov_matrix(doc)
    apply_formula_explanations(doc)
    apply_ppo_rationale(doc)
    apply_reader_facing_replacements(doc)
    apply_scope_and_future_work(doc)
    insert_pipeline_figure(doc)
    add_references(doc)
    simplify_dense_table_labels(doc)
    clean_encoding_artifacts(doc)
    disable_auto_hyphenation(doc)
    doc.save(DST)
    print(f"Wrote {DST.relative_to(ROOT)}")

    if export_pdf():
        print(f"Wrote {PDF.relative_to(ROOT)}")
    else:
        print(f"PDF export failed; DOCX remains available at {DST.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
